### PR TITLE
Update ClusterSignificance

### PR DESCRIPTION
**Pull request by rcannood**
Hello all,

I have now run revdep for princurve on bioconductor packages. I fixed a bug caused in princurve where it would not correctly set the dimnames of the outputted object (dynverse/princurve@41a5af8d94ab888619830d2fafa6a0c2183ee764). In the meantime, this pull request makes the necessary changes required for the future deprecation of the `principal.curve` function.

Could you confirm whether everything is working now?

I've temporarily added a Remotes: in the DESCRIPTION. Upon your confirmation, I will submit princurve 2.0.5 to CRAN. I'll let you know when it is accepted, so you can remove the Remotes: from the DESCRIPTION.

Is this okay for you?

Kind regards,
Robrecht

### CODE REVIEW

**Comment by jasonserviss** [comment]
@rcannood It appears as though everything is in order! I have now pushed the changes to Bioconductor and the package will most likely re-build tonight. Ill have a look tomorrow morning and make sure there were no hiccups (if there were it would probably be me adding the changes to Bioconductor) and let you know. Thanks for handling the "heavy lifting". Much appreciated!

**Comment by rcannood** [comment]
Good to hear everything is working at your end :+1:

Did you submit ClusterSignificance to Bioconductor including the `Remotes: dynverse/devtools@devel` in the DESCRIPTION? Does Bioconductor allow for GitHub repositories to be added this way?

Tomorrow, I will add some more tests to princurve and submit version 2.0.5 to CRAN. Once accepted, you can remove the `Remotes: ...` line from the DESCRIPTION.

**Comment by jasonserviss** [comment]
Yes, I left the Remotes. Not sure if Bioconductor allows it, although, I would imagine if they didn't that it would have been detected by BiocCheck. I figured, worst case scenario, the build will continue to fail until I can remove the Remotes after you submit 2.0.5 to CRAN.

**Comment by rcannood** [comment]
Fair enough :)

**Comment by jasonserviss** [comment]
@rcannood just FYI, according to the latest [build report](https://master.bioconductor.org/checkResults/3.7/bioc-LATEST/ClusterSignificance/malbec2-install.html) it doesn't look as though the REMOTES is working on Bioconductors build servers (I am actually not too surprised). Any time line for submission to CRAN?

**Comment by rcannood** [comment]
Okay! Today I've put quite a bit of effort writing more unit tests to ensure everything I won't be needing to bother the people at CRAN with frequent resubmissions of princurve. I've managed to find and fix a few more bugs in the old princurve code, but I'm not fully satisfied yet. I should be able to submit version 2.0.5 tomorrow, worst case by Monday. Is this okay for you?

**Comment by jasonserviss** [comment]
More than ok for me... was just curious to know the approximate time frame.

**Comment by rcannood** [comment]
The new version of princurve is available on CRAN :) As i added quite a few optimisations, i ended up calling it princurve 2.1.0. A revdepcheck showed that Cluste should be working, so you can remove the 'remotes' from the description and let Bioconductor rebuild :)

**Comment by jasonserviss** [comment]
Alright, great! I removed princurve from Remotes and the build on TravisCI looks good. Hopefully, it will build tonight on Bioconductor and I will confirm that everything is working.

**Comment by jasonserviss** [comment]
Looks like everything is in order now! Thanks again for all your help resolving this!

**Comment by rcannood** [comment]
Good to hear!

**Pull request merged**
